name: searchEngine
channels:
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
      - chardet==5.2.0
      - dill==0.3.8
      - pillow==10.3.0
      - pymupdf==1.24.5
      - reportlab==4.2.2
